### ISSUE TITLE
Coudn´t compile

### ISSUE THREAD

**Issue by marrobHD** [lewisxhe/esp32-dash#2]
It wont compile
src\main.cpp: In function 'bool serverBegin()':
src\main.cpp:53:22: error: could not convert 'ESPDash.ESPDashClass::init(server)' from 'void' to 'bool'
if (!ESPDash.init(server)) { // Initiate ESPDash and attach your Async webserver instance
^
src\main.cpp:53:29: error: in argument to unary !
if (!ESPDash.init(server)) { // Initiate ESPDash and attach your Async webserver instance
^
Compiling .pioenvs\ttgo-t-beam\lib75e\WiFi\WiFiUdp.cpp.o
*** [.pioenvs\ttgo-t-beam\src\main.cpp.o] Error 1
 [ERROR] Took 9.64 seconds

**Comment by brupje** [comment]
Upgrade ESP-DASH library to master
If you are using latest ArduinoJSON, replace all lines 
#elif ARDUINOJSON_VERSION_MAJOR == 6 && ARDUINOJSON_VERSION_MINOR == 8
with
#elif ARDUINOJSON_VERSION_MAJOR == 6 && ARDUINOJSON_VERSION_MINOR >= 8

in ESPDash.cpp
